### ISSUE TITLE
`gdalinfo --formats` not matching

### ISSUE THREAD

**Issue by rvvincelli** [webmapp/gdal-docker#24]
Hi! Thank you for this handy image :) The supported formats list does not match with what I see in the readme, in particular no `PostgreSQL` is found. Hints? :)

**Comment by wchatx** [comment]
@rvvincelli thanks for using the image! 

I typically only deal with vector datasets so pardon my ignorance if I'm mistaken, but this is working as expected for me.
```
docker run -it webmapp/gdal-docker:latest gdalinfo --formats | grep PostGISRaster
```
The formats listed in the README correspond to the output of `ogr2ogr --formats`

**Comment by rvvincelli** [comment]
@wchatx Thank you! Sorry for this report this is actually a little misunderstanding of mine, confusing the outputs of `gdalinfo --formats` and `ogr2ogr --formats` :)

**Comment by wchatx** [comment]
No problem!
